-- Generated by drizzle-kit from the schema change in server/db/schema.ts.
--
-- The `reauthenticated_at` statement is made idempotent on purpose. Migration
-- 0001 already added that column with IF NOT EXISTS, and databases that ran it
-- would fail on a bare ADD COLUMN, so re-running must not break an existing
-- install. Fresh databases get the column from 0001 as well; the statement is
-- kept here so this migration also repairs an install that predates it.

DROP INDEX IF EXISTS "login_attempts_scope_idx";--> statement-breakpoint
ALTER TABLE "sessions" ADD COLUMN IF NOT EXISTS "reauthenticated_at" timestamp with time zone;--> statement-breakpoint
CREATE UNIQUE INDEX IF NOT EXISTS "login_attempts_scope_key" ON "login_attempts" USING btree ("scope");
